sudo: required

# not necessary, but less confusing if defined
language: python

services:
  - docker

env:
  - DISTRO=debian:stable PYTHON="2"
  - DISTRO=debian:stable PYTHON="3" # 3.4, not 3.5
  - DISTRO=debian:stable PYTHON="3" KRB5_VER="heimdal"
  - DISTRO=centos:7 PYTHON="2" # el7 doesn't do python3 modules
  - DISTRO=fedora:rawhide PYTHON="3"
  - DISTRO=fedora:rawhide PYTHON="2"

script:
  - sudo sed -i '1i 127.0.0.1 test.box' /etc/hosts
  - sudo hostname test.box
  - >
    docker run
    -v `pwd`:/tmp/build
    -w /tmp/build
    -e KRB5_VER=$KRB5_VER
    -e PYTHON=$PYTHON
    $DISTRO
    /bin/bash -ex .travis.sh

before_deploy:
  - >
    docker run
    -v `pwd`:/tmp/build
    -w /tmp/build
    -e KRB5_VER=$KRB5_VER
    -e PYTHON=$PYTHON
    $DISTRO
    /bin/sh -x .travis.before-deploy.sh
deploy:
  - provider: releases
    api_key:
      secure: U8RPR6liglI4J8MOSEyK9uxvSFRMcCkKLflpIFKcpUFg+PUuK85YtRdOOL/L/pifat9/KvoF7OJEMNTQjoYAhziMu8GGsiPZlkFzXNiy54FxTTtgprkhllRK7nw/jK/hopKM01goKVaUL860aU+KdpfStRTaAy8ZGEj13jwOMYU=
    file_glob: true
    file:
      - tag_build/*
    on:
      repo: pythongssapi/python-gssapi
      tags: true
      condition: "$DISTRO = 'fedora:rawhide' && $PYTHON = '3'"
    skip_cleanup: true
  - provider: pypi
    user:
      secure: gMwGf6Zt2BuPHN6Qy4feaJaZQBIYZ1lZIdFcpugyhnWtxytzwApx2LTXqHgdaVK7Ik6Xk97RmWS5SyciKmC2V1nyaHCX/f31QZAD3TrLqhScPtvE6j9j/srJhDBjp5yAT8NENMykeSvoIhiidw1tPzWYRW9c93roaOUv6Kqd3zc=
    password:
      secure: D0lX+DRVac2GN3bZuKxd45DluBrcvwMfV+cciannEJ39kjbHTQEdpi0Uv92rDLNicjqyjy9rAEP7UAQQ1GDOvZcN5OG1+uWU1tSV84uKPgT92YbbQQdHRs/Rh3KSHKeaiJ+3TTDSeBuXYgWRs2gCeVAb18LBYjtIHLZxCFB8ln0=
    on:
      repo: pythongssapi/python-gssapi
      tags: true
      condition: "$DISTRO = 'fedora:rawhide' && $PYTHON = '3'"
    skip_cleanup: true
    docs_dir: travis_docs_build/html
